server:
  port: 9003
spring:
  application:
    name: talk-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 246222
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.qa.pojo
  mapper-locations: classpath:/Dao/*Dao.xml
